-- Create sensitivity tag and apply classification to core tables.
-- Co-authored with CoCo

--------------------------------------------------------------------------------
-- KA_TAG_CONTENT_SENSITIVITY — Content Sensitivity Classification
--
-- Four-tier classification:
--   RESTRICTED   — PHI, patient-identifiable content (future use)
--   CONFIDENTIAL — Internal review decisions, compliance findings
--   INTERNAL     — General knowledge base documents
--   PUBLIC       — Approved content cleared for external sharing
--
-- Best practice: SYSADMIN owns the schema objects and can create/manage tags
-- on tables it owns. Tags are schema-level objects owned by the schema owner.
--------------------------------------------------------------------------------

USE ROLE SYSADMIN;
USE DATABASE DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS;
USE SCHEMA SCHEMA_HEALTHCARE_KNOWLEDGE;

CREATE OR REPLACE TAG DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS.SCHEMA_HEALTHCARE_KNOWLEDGE.KA_TAG_CONTENT_SENSITIVITY
    ALLOWED_VALUES 'RESTRICTED', 'CONFIDENTIAL', 'INTERNAL', 'PUBLIC';

--------------------------------------------------------------------------------
-- Apply tags to tables
--------------------------------------------------------------------------------

-- CURATED_TBL_DOCUMENTS: general knowledge base content = INTERNAL
ALTER TABLE DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS.SCHEMA_HEALTHCARE_KNOWLEDGE.CURATED_TBL_DOCUMENTS
    SET TAG DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS.SCHEMA_HEALTHCARE_KNOWLEDGE.KA_TAG_CONTENT_SENSITIVITY = 'INTERNAL';

-- CURATED_TBL_COMPLIANCE_FINDINGS: compliance/gap analysis = CONFIDENTIAL
ALTER TABLE DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS.SCHEMA_HEALTHCARE_KNOWLEDGE.CURATED_TBL_COMPLIANCE_FINDINGS
    SET TAG DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS.SCHEMA_HEALTHCARE_KNOWLEDGE.KA_TAG_CONTENT_SENSITIVITY = 'CONFIDENTIAL';

-- HITL_TBL_REVIEW_DECISIONS: human review decisions = CONFIDENTIAL
ALTER TABLE DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS.SCHEMA_HEALTHCARE_KNOWLEDGE.HITL_TBL_REVIEW_DECISIONS
    SET TAG DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS.SCHEMA_HEALTHCARE_KNOWLEDGE.KA_TAG_CONTENT_SENSITIVITY = 'CONFIDENTIAL';


--

SELECT *
FROM TABLE(DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS.INFORMATION_SCHEMA.TAG_REFERENCES(
    'DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS.SCHEMA_HEALTHCARE_KNOWLEDGE.CURATED_TBL_DOCUMENTS',
    'TABLE'
));

SELECT *
FROM TABLE(DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS.INFORMATION_SCHEMA.TAG_REFERENCES(
    'DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS.SCHEMA_HEALTHCARE_KNOWLEDGE.CURATED_TBL_COMPLIANCE_FINDINGS',
    'TABLE'
));

SELECT *
FROM TABLE(DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS.INFORMATION_SCHEMA.TAG_REFERENCES(
    'DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS.SCHEMA_HEALTHCARE_KNOWLEDGE.HITL_TBL_REVIEW_DECISIONS',
    'TABLE'
));