-- Create the KA_CONFIG table for runtime configuration values (idempotent)
-- Co-authored with CoCo

USE ROLE SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_ROLE;
USE WAREHOUSE SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_WH;
USE DATABASE SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_DB;
USE SCHEMA CONFIG;

CREATE TABLE IF NOT EXISTS KA_CONFIG (
    CONFIG_KEY   VARCHAR PRIMARY KEY,
    CONFIG_VALUE VARCHAR,
    DESCRIPTION  VARCHAR,
    UPDATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Verification: confirm column structure matches spec
DESCRIBE TABLE KA_CONFIG;