-- Create database, schema, and role for Healthcare Knowledge Agent (idempotent)
-- Co-authored with CoCo

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS;
CREATE SCHEMA IF NOT EXISTS DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS.SCHEMA_HEALTHCARE_KNOWLEDGE;

USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS ROLE_SCHEMA_HEALTHCARE_KNOWLEDGE;

-- Verification
SHOW DATABASES LIKE 'DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS';
SHOW SCHEMAS IN DATABASE DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS;
SHOW ROLES LIKE 'ROLE_SCHEMA_HEALTHCARE_KNOWLEDGE';