-- Create the KA_CONFIG table for runtime configuration values (idempotent)
-- Co-authored with CoCo

USE ROLE ROLE_SCHEMA_HEALTHCARE_KNOWLEDGE;
USE WAREHOUSE WH_HCLS_XS;
USE DATABASE DB_SNOWFLAKE_ENTERPRISE_AGENTS_HCLS;
USE SCHEMA SCHEMA_HEALTHCARE_KNOWLEDGE;

CREATE TABLE IF NOT EXISTS KA_CONFIG (
    CONFIG_KEY   VARCHAR PRIMARY KEY,
    CONFIG_VALUE VARCHAR,
    DESCRIPTION  VARCHAR,
    UPDATED_AT   TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Verification: confirm column structure matches spec
DESCRIBE TABLE KA_CONFIG;