-- Create database, schema, and role for Healthcare Knowledge Agent (idempotent)
-- Co-authored with CoCo

USE ROLE SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_ROLE;

USE DATABASE SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_DB;

CREATE SCHEMA IF NOT EXISTS SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_DB.SCHEMA_HEALTHCARE_KNOWLEDGE;
CREATE SCHEMA IF NOT EXISTS SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_DB.CONFIG;
CREATE SCHEMA IF NOT EXISTS SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_DB.CURATED;
CREATE SCHEMA IF NOT EXISTS SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_DB.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_DB.SEMANTICS;
CREATE SCHEMA IF NOT EXISTS SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_DB.GEN_AGENTIC_AI;


USE ROLE SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_ROLE;

-- CREATE ROLE IF NOT EXISTS SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_ROLE;

-- Verification
SHOW DATABASES LIKE 'SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_DB';
SHOW SCHEMAS IN DATABASE SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_DB;
SHOW ROLES LIKE 'SEA_HEALTHCARE_KNOWLEDGE_AGENT_OWNER_ROLE';